name: Sync Security Hub findings and Jira issues

on:
  push:
    branches: [entjira]
  workflow_dispatch: # for testing and manual runs
  schedule:
    - cron: "0 6 * * *" # daily at 0600 UTC

permissions:
  id-token: write

jobs:
  sync:
    name: Run sync
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.PRODUCTION_SYNC_OIDC_ROLE }}
      - name: Sync Security Hub and Jira
        uses: Enterprise-CMCS/mac-fc-security-hub-visibility@v2.7.0
        with:
          jira-token: ${{ secrets.JIRA_TEMP_USER_TOKEN }}
          jira-username: ${{ secrets.JIRA_TEMP_USERNAME }}
          jira-host: jiraent.cms.gov
          jira-project-key: CMDCT
          #jira-epic-key: MDCT-2280
          jira-ignore-statuses: Done, Closed, Canceled
          #jira-custom-fields: '{ "customfield_14154" : [{"id": "16986", "value": "MFP"}] }'
          aws-severities: CRITICAL, HIGH, MEDIUM
          is_jira_enterprise: true
